"""Создание таблиц в БД

Revision ID: 3f7980d6e5b5
Revises: 
Create Date: 2026-07-21 21:23:47.115047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f7980d6e5b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hash_pwd', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token')
    )
    op.create_table('vacancy_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('experience', sa.String(length=255), nullable=False),
    sa.Column('work_format', sa.String(length=255), nullable=False),
    sa.Column('common_employment', sa.String(length=255), nullable=False),
    sa.Column('work_schedule', sa.String(length=255), nullable=False),
    sa.Column('work_hours', sa.String(length=255), nullable=False),
    sa.Column('name_company', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('count_payments', sa.String(length=255), nullable=False),
    sa.Column('detailed_information', sa.Text(), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('salary', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_info')
    op.drop_table('users')
    # ### end Alembic commands ###
